# Generated by Django 3.1.2 on 2021-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210103_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountgroup',
            name='products',
            field=models.ManyToManyField(related_name='discount_group', to='product.Product'),
        ),
    ]
