# Generated by Django 3.1.2 on 2021-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210103_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Feature Name')),
                ('value', models.CharField(max_length=20, verbose_name='Feature Value')),
            ],
        ),
        migrations.RemoveField(
            model_name='featureoptions',
            name='feature_option_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='FeatureOptionGroups',
        ),
        migrations.DeleteModel(
            name='FeatureOptions',
        ),
        migrations.DeleteModel(
            name='ProductTags',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='product.Feature'),
        ),
    ]
