# Generated by Django 3.1.2 on 2021-01-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210104_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuregroup',
            name='features',
        ),
        migrations.AddField(
            model_name='featuregroup',
            name='features',
            field=models.ManyToManyField(related_name='features', to='product.Feature'),
        ),
        migrations.RemoveField(
            model_name='featuregroup',
            name='products',
        ),
        migrations.AddField(
            model_name='featuregroup',
            name='products',
            field=models.ManyToManyField(related_name='product_features', to='product.Product'),
        ),
    ]
