# Generated by Django 3.1.2 on 2021-01-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_filterfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='Feature Key')),
            ],
        ),
        migrations.RemoveField(
            model_name='filterfeature',
            name='key',
        ),
        migrations.AddField(
            model_name='filterfeature',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.allfeature'),
        ),
    ]
