# Generated by Django 3.1.2 on 2021-01-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210107_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Feature Name'),
        ),
    ]
