# Generated by Django 3.1.2 on 2021-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210107_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsoptions',
            name='brand_group',
        ),
        migrations.RemoveField(
            model_name='brandsoptions',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='pricerangeoptions',
            name='price_range_group',
        ),
        migrations.RemoveField(
            model_name='quantityoptions',
            name='quantity_option_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='BrandGroup',
        ),
        migrations.DeleteModel(
            name='BrandsOptions',
        ),
        migrations.DeleteModel(
            name='PriceRangeGroup',
        ),
        migrations.DeleteModel(
            name='PriceRangeOptions',
        ),
        migrations.DeleteModel(
            name='QuantityOptionGroup',
        ),
        migrations.DeleteModel(
            name='QuantityOptions',
        ),
    ]
