# Generated by Django 3.1.2 on 2021-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210107_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Feature Name'),
        ),
    ]
