# Generated by Django 3.1.2 on 2020-11-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecom_backend.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBusinessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('pancard', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Pan Card')),
                ('adharCard', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Aadhar Card')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Logo')),
                ('shop_board', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Board Picture')),
                ('role', models.IntegerField(choices=[(1, 'Retailer'), (2, 'Whole Seller')], default=1)),
                ('minimum_home_delivery', models.IntegerField(blank=True, null=True)),
                ('shop_category', models.IntegerField(choices=[(1, 'Category1'), (2, 'Category2')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pincode')),
            ],
        ),
        migrations.CreateModel(
            name='SellerBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(max_length=20)),
                ('acc_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('acc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_proof', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Document For Bank Proof')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerbankdetail')),
                ('business_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerbusinessdetail')),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerpersonaldetail')),
            ],
        ),
    ]
