# Generated by Django 3.1.2 on 2020-12-03 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecom_backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('pancard', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Pan Card')),
                ('adharcard', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Aadhar Card')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Logo')),
                ('board', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Board Picture')),
                ('role', models.IntegerField(choices=[(1, 'Retailer'), (2, 'Whole Seller')], default=1)),
                ('minimum_order', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Category1'), (2, 'Category2')], default=1)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(max_length=20)),
                ('account_holder', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.CharField(blank=True, max_length=20, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Document For Bank Proof')),
                ('bank_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pincode')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerpersonaldetail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellerpersonaldetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerpersonaldetail',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='bank_detail',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='business_detail',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='personal_detail',
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SellerBankDetail',
        ),
        migrations.DeleteModel(
            name='SellerBusinessDetail',
        ),
        migrations.DeleteModel(
            name='SellerPersonalDetail',
        ),
        migrations.AddField(
            model_name='seller',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerdetail'),
        ),
    ]
