# Generated by Django 3.1.2 on 2020-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20201203_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetail',
            name='shop_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
