# Generated by Django 3.1.2 on 2020-12-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_sellerdetail_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetail',
            name='category',
            field=models.IntegerField(choices=[(1, 'Only Home Delivery'), (2, 'Only Pick Up'), (3, 'Both')], default=3),
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='role',
            field=models.IntegerField(choices=[(1, 'Retailer'), (2, 'Distributor'), (3, 'Whole Seller')], default=1),
        ),
    ]
