# Generated by Django 3.1.2 on 2021-01-04 14:56

from django.db import migrations, models
import ecom_backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20201203_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetail',
            name='adharcard',
            field=models.FileField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Aadhar Card'),
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='board',
            field=models.FileField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Board Picture'),
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Shop Logo'),
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Pan Card'),
        ),
        migrations.AlterField(
            model_name='sellerdetail',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Document For Bank Proof'),
        ),
    ]
