# Generated by Django 3.1.2 on 2021-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20210105_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetail',
            name='pincodes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
