# Generated by Django 3.1.2 on 2020-11-27 09:06

from django.db import migrations, models
import django.db.models.deletion
import ecom_backend.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1)),
                ('date_comment', models.DateField(auto_now_add=True, verbose_name='date of comment')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecom_backend.utils.upload_image, verbose_name='Upload Blog Image')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Blog')),
                ('comment', models.ManyToManyField(blank=True, to='blog.BlogComment')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogimages')),
                ('tags', models.ManyToManyField(blank=True, to='blog.BlogTags')),
            ],
        ),
    ]
