# Generated by Django 3.1.2 on 2020-12-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20201129_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='name_on_card',
            new_name='card_name',
        ),
    ]
