# Generated by Django 3.1.2 on 2021-01-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20201201_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
