# Generated by Django 3.1.2 on 2020-11-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.JSONField(null=True)),
                ('features', models.JSONField(null=True)),
                ('shipping_address', models.JSONField(null=True)),
                ('is_billing_same', models.BooleanField(default=True)),
                ('billing_address', models.JSONField(null=True)),
                ('track_dates', models.JSONField(null=True)),
                ('return_policy', models.JSONField(null=True)),
                ('payment_option', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('is_return_available', models.BooleanField(default=True)),
                ('is_cancel_available', models.BooleanField(default=True)),
                ('track_status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Shipped'), (3, 'Out For Delivery'), (4, 'Delivered')], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('measurement_parameter', models.CharField(max_length=10)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
